rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx
  - jruby-19mode
  - jruby-20mode

script: "bundle exec rake"

gemfile:
  - gemfiles/4.0.gemfile

matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby-19mode
    - rvm: jruby-20mode
