rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - rbx
  - jruby-19mode
  - jruby-20mode

script: "bundle exec rspec"

gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.0.gemfile
  
matrix:
  allow_failures:
    - rvm: rbx
